//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airline_Reservation.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.Cancellations = new HashSet<Cancellation>();
            this.Passengers = new HashSet<Passenger>();
        }
    
        public int BookingId { get; set; }
        public int FlightId { get; set; }
        public string Class { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
        public System.DateTime DateOfBooking { get; set; }
        public System.DateTime DateOfJourney { get; set; }
        public int NoOfSeats { get; set; }
        public decimal TicketFare { get; set; }
        public int CustomerId { get; set; }
        public string TicketStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cancellation> Cancellations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Passenger> Passengers { get; set; }
        public virtual Booking Bookings1 { get; set; }
        public virtual Booking Booking1 { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Flight Flight { get; set; }
    }
}
