//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airline_Reservation.web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Flight
    {
        [Required]
        public int FlightId { get; set; }
        [Required]
        public string FlightName { get; set; }
        [Required]
        public string Source { get; set; }
        [Required]
        public string Destination { get; set; }
        [Required]
        public Nullable<System.DateTime> DepartureTime { get; set; }
        [Required]
        public Nullable<System.DateTime> ArrivalTime { get; set; }
        [Required]
        public int BaggageLimit { get; set; }
        [Required]
        public int AvailableSeats { get; set; }
    }
}
